# Change these first
owner: mhmdsyq # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Mydin Express
    url: https://mydinexpress.my/hypermart/
  - name: Lotus
    url: https://corp.lotuss.com.my/
  - name: Aeon
    url: https://www.aeonretail.com.my/
  - name: Giant
    url: https://www.giant.com.my/

status-website:
  theme: night
  baseUrl: https://mhmdsyq.github.io/upptime/ # where "repo" is your repository name
  name: Upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
